freeze-lava: true
debug: false
material-list:
- RAILS
- POWERED_RAIL
- ACTIVATOR_RAIL
- DETECTOR_RAIL
- REDSTONE
- REDSTONE_COMPARATOR
- REDSTONE_COMPARATOR_OFF
- REDSTONE_COMPARATOR_ON
- REDSTONE_ORE
- REDSTONE_TORCH_OFF
- REDSTONE_TORCH_ON
- REDSTONE_WIRE
- DIODE
- DIODE_BLOCK_OFF
- DIODE_BLOCK_ON