name: Glacier
version: 1.7.2-2
description: Efficient multiplayer-friendly liquids.
author: [SyntaxNode, zifnab06]
website: http://junction.at/

main: at.junction.glacier.Glacier
database: true
depend: [WorldGuard]

commands:
  freeze:
    description: Toggle between static and flowing water blocks.
    permission: glacier.toggle
    usage: |
      /freeze

permissions:
  glacier.flowing:
    description: Allows a player to place flowing liquids.
    default: false
  glacier.toggle:
    description: Allows a player to toggle between static and flowing water blocks.
    default: true
